name: Build YO Log PRO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout cod
      uses: actions/checkout@v4

    - name: Setare Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalare PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Construire Executabil
      run: |
        pyinstaller --noconsole --onefile --name "YOLogPRO_v9" --collect-all tkinter yo_log_pro.py

    - name: Incarcare Executabil
      uses: actions/upload-artifact@v4
      with:
        name: YO-Log-PRO-EXE
        path: dist/YOLogPRO_v9.exe
